import {Accounts} from 'meteor/accounts-base';

const buildEmailDefaults = (RocketChat) => {
	const siteName = RocketChat.settings.get('Site_Name') || 'Strata.chat';
	const header = RocketChat.placeholders.replace(RocketChat.settings.get('Email_Header') || '');
	const footer = RocketChat.placeholders.replace(RocketChat.settings.get('Email_Footer') || '');
	const fromEmail = RocketChat.settings.get('From_Email') || 'no-reply@strata.chat';
	const fromEmailString = `${RocketChat.settings.get('Site_Name')} <${fromEmail}>`;
	const verifyEmailSubject = `Please verify your ${siteName} account.`;
	const verifyEmailContent = `Hi - welcome to ${siteName}.\n
		To verify your account email, simply click this link - __URL__\n
		If you can't click the link, copy and paste the entire URL into your browser.\n\n
		The Strata.chat team.`;
	const passwordResetEmailSubject = `How to reset your password on ${siteName}`;
	const passwordResetEmailContent = `Hi - To reset your ${siteName} password,\n
		simply click this link - __URL__\n
		If you can't click the link, copy and paste the entire URL into your browser.\n\n
		The Strata.chat team.`;
	return {
		header,
		footer,
		fromEmail,
		fromEmailString,
		verifyEmailSubject,
		verifyEmailContent,
		passwordResetEmailSubject,
		passwordResetEmailContent
	};
};

Meteor.startup(() => {
	/*
	 * Common to all emails generated by the Accounts package
	 */
	const emailDefaults = buildEmailDefaults(RocketChat);
	Accounts.emailTemplates.siteName = emailDefaults.siteName;
	Accounts.emailTemplates.from     = emailDefaults.fromEmailString;

	/*
	 * Verification Email
	 */
	Accounts.emailTemplates.verifyEmail.subject = (user) => {
		return emailDefaults.verifyEmailSubject;
	};
	Accounts.emailTemplates.verifyEmail.text    = (user, url) => {
		return emailDefaults.verifyEmailContent.replace('__URL__', url);
	};
	Accounts.emailTemplates.verifyEmail.html    = (user, url) => {
		const html = emailDefaults.verifyEmailContent
			.replace('__URL__', url)
			.replace(/\n/g, '<br>');
		return `${emailDefaults.header} ${html} ${emailDefaults.footer}`;
	};

	/*
	 * Password Reset Email
	 */
	Accounts.emailTemplates.resetPassword.subject = (user) => {
		return emailDefaults.passwordResetEmailSubject;
	};
	Accounts.emailTemplates.resetPassword.text    = (user, url) => {
		return emailDefaults.passwordResetEmailContent.replace('__URL__', url);
	};
	Accounts.emailTemplates.resetPassword.html    = (user, url) => {
		const html = emailDefaults.passwordResetEmailContent
			.replace('__URL__', url)
			.replace(/\/#\//, '/')
			.replace(/\n/g, '<br>');
		return `${emailDefaults.header} ${html} ${emailDefaults.footer}`;
	};
});

